- name: Ensure services are started                                                                                                                                                                        
  notify: Restart httpd
  loop: "{{ service }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped

