- name: cat files
  hosts: all
  tasks:
    - name: cat /etc/hosts
      ansible.builtin.command: cat /etc/hosts
      register: results

    - name: display results
      ansible.builtin.debug:
        msg: "{{ results.stdout_lines }}"

    - name: copy file to dest
      ansible.builtin.copy:
        src: lite.yml
        dest: /tmp/ansible/

    - name: copy file to dest folder with variable
      ansible.builtin.copy:
        src: lite.yml
        dest: "/tmp/ansible/{{ ansible_facts['hostname'] }}/"
